
server:
    port: 8082

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/micro2
        username: root
        password: pass
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    application:
        name: QUESTION-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

